### ISSUE TITLE
Addition of a drop down menu to select the index plate in micro library prep

### ISSUE THREAD

**Issue by AbiDalby** [Clinical-Genomics/cg_lims#501] opened 2024-05-15 10:28 UTC
Lims Issue - Addition of a drop down menu to select the index plate in micro library prep
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:**  Microbial WGS v7
**Protocol:** Nextera Microbial WGS v4
**Step:** Microbial Library Prep (Nextera) v2

**Description:** Following the deviation [Incorrect index added in lims for microbial samples](https://github.com/Clinical-Genomics/Deviations/issues/647#top)
#647. A suggestion for adding a drop-down menu to select which index plate is taken before adding the labels to the samples in lims was proposed. The TGA protocol already utilises this function and so it should be possible to implement.

Currently during the Nextera microbial library prep, the indicies from all plates are in one long list and there is a risk that the lab personnel only ensure that the *well placement is correct* (e.g. label A1 to sample A1) and miss the *ID of the plate* (e.g. Plate 4).

**Comment by idalindegaard** [comment] 2024-05-21 14:04
I split the information in the index label list that we had in LIMS with all index sets into four index label documents with Set 1-4. 
I tested it in LIMS stage and it looks like it should in the label options etc:

<img width="745" alt="Screenshot 2024-05-21 at 16 01 25" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/151ad79b-441d-4879-8dc5-b39068cec5aa">
<img width="777" alt="Screenshot 2024-05-21 at 16 01 51" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/ade64b8f-2799-44da-8af2-5f73570cb252">
<img width="263" alt="Screenshot 2024-05-21 at 16 02 30" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/22f4a9a5-93e6-479c-927a-6d9b0dbbbbbd">

**Comment by idalindegaard** [comment] 2024-05-21 14:13
@AbiDalby the issue is fixed now, if you want to update the deviation!

**Closed** 2024-05-21 14:13 UTC

**Comment by AbiDalby** [comment] 2024-05-22 06:41
Perfect. Looks great! The deviation has been updated and is closed.
